### ISSUE TITLE
Conversion script adds incorrect PDDL requirements

### ISSUE THREAD

**Issue by jendrikseipp** [ipc2023-classical/ipc2023-dataset#1]
Hi @danfis !
For all four domains that had normalized versions in the IPC, I get the following requirements, when I run the conversion Apptainer script:

```
(:requirements
    :strips
    :typing
    :negative-preconditions
    :disjunctive-preconditions
    :equality
    :existential-preconditions
    :universal-preconditions
    :conditional-effects
)
```

But isn't the whole point that the script removes some of these?

**Comment by danfis** [comment]
Sun, Apr 14, 2024 at 11:29:21PM CEST, ***@***.***:
> Hi @danfis !
> For all four domains that had normalized versions in the IPC, I get the following requirements, when I run the conversion Apptainer script:
> 
> ```
> (:requirements
>     :strips
>     :typing
>     :negative-preconditions
>     :disjunctive-preconditions
>     :equality
>     :existential-preconditions
>     :universal-preconditions
>     :conditional-effects
> )
> ```
> 
> But isn't the whole point that the script removes some of these?
It seems the translator keeps the :requirements from the input pddl
untouched. The actual features should be compiled away. Thanks for pointing
this out, I'll put this on my todo list to fix it. I think I didn't notice
because most translators just ignore requirements (for example Fast
Downward), or are ok with having superset of features appearing in the pddl
file (which is a correct behaviour).

For now, if you need accurate :requirements section, I would suggest using
sed as postprocessing step (sed -i 's/:unwanted-feature//' domain.pddl).

Cheers,
   Dan

**Comment by jendrikseipp** [comment]
Thanks! Yes, that's the approach I used to fix this. Just wanted to mention it here, so you have it on your radar.

**Comment by danfis** [comment]
Hi Jendrik,
I just pushed some changes that should fix this issue. Now, the tool infers the right (minimal) :requirements flags.
Please, give it a try and let me know if you spot any issue.

Cheers,
   Dan

**Comment by jendrikseipp** [comment]
Great, thanks!
